In [ ]:
### numpy -> Play with arrays(Numbers)
### pandas -> Datasets
### matplotlib -> Data visualizations
### seaborn -> Data visualizations
### scipy -> Statistical
### sklearn -> Algorithm

### Numpy: Packages for Multidimensional Array

In [7]:
import numpy as np

In [8]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [9]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [11]:
list_of_list=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [14]:
np.arange(1,36,5)

array([ 1,  6, 11, 16, 21, 26, 31])

In [15]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [16]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [19]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.ones((2,3),int)

array([[1, 1, 1],
       [1, 1, 1]])

In [21]:
np.ones((50,50),int)

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [22]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [23]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [24]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [25]:
np.random.rand(3,5)

array([[0.35385964, 0.04558089, 0.59126485, 0.54179479, 0.99760917],
       [0.02427687, 0.48621807, 0.52461173, 0.92031611, 0.30569257],
       [0.14743097, 0.32829639, 0.55351283, 0.99876843, 0.64651734]])

In [26]:
arr=np.random.randn(2,4)
arr

array([[-1.70413271, -0.40731507, -0.39262417, -0.14688474],
       [ 0.91631825, -2.42470956,  0.51478986, -0.37242339]])

In [28]:
np.random.randint(2,100)

82

In [30]:
np.random.randint(20,56,100)

array([48, 33, 26, 30, 39, 24, 54, 35, 31, 24, 51, 34, 48, 36, 24, 28, 45,
       37, 54, 46, 54, 51, 50, 30, 25, 53, 29, 44, 46, 32, 29, 47, 34, 24,
       53, 43, 33, 29, 36, 44, 42, 50, 26, 31, 29, 28, 31, 54, 30, 47, 41,
       35, 30, 27, 35, 20, 47, 22, 52, 36, 53, 55, 23, 28, 52, 42, 35, 49,
       28, 48, 45, 45, 23, 33, 38, 50, 30, 37, 29, 43, 55, 32, 33, 41, 38,
       42, 53, 20, 23, 32, 55, 55, 24, 55, 26, 26, 48, 20, 53, 30])

In [32]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [33]:
rand_array=np.random.randint(0,10,50)
rand_array

array([4, 4, 6, 5, 0, 1, 6, 8, 9, 0, 3, 2, 3, 9, 2, 2, 6, 3, 6, 0, 3, 5,
       0, 7, 8, 4, 3, 8, 2, 2, 1, 5, 9, 3, 1, 7, 3, 2, 0, 2, 3, 6, 0, 3,
       0, 3, 0, 0, 9, 5])

In [34]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [36]:
rand_array.max()

9

In [37]:
rand_array.argmax()

8

In [39]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
a=np.random.rand(2,3)
a

array([[0.94368235, 0.71235776, 0.48162293],
       [0.98527239, 0.83511016, 0.2835829 ]])